Mysql:
  Host: "115.190.54.31"
  Port: 3306
  User: "root"
  Password: "4ay1nkal3u8ed77y"
  Database: "day25"

Redis:
  Host: "115.190.54.31"
  Port: 6379
  Password: "4ay1nkal3u8ed77y"
  Database: 0

Consul:
  Host: "115.190.54.31"
  Port: 8500
  ServiceName: "basic-service"
  ServicePort: 50051
  TTL: 30